// src/constants/Screen.js

const Screen = {
  Welcome: 'welcome',
  Login: 'loginScreen',
  MainTabs: 'mainTabs',
  Home: 'homeScreen',
  Hub: 'hubScreen',
  MoreScreen: 'moreScreen',
  OrganizationDetail: 'organizationDetail',
  PrivacyPolicy: 'privacyPolicy',
  MyProfile: 'myprofile',
  Note: 'note',
  ChangePassword: 'changePassword',
  ForgotPassword: 'forgotPassword',
  VerificationScreen: 'verification',
  NonMemberEmail: 'nonMemberEmail',
  NonMemberInfo: 'nonMemberInfo',
  NonMemberVerification: 'nonMemberVerification',
  ResetPasswordScreen: 'resetPassword',
  EventDetailScreen: 'eventDetail',
  EventRegistrationAsScreen: 'eventRegistrationAs',
  GuestScreen: 'guestScreen',
  OrganizationChart: 'organizationChart',
  SignUp: 'signup',
  GuestDetail: 'guestDetail',
  NetworkError: 'networkError',
  Benefit: 'benefit',
  DeleteAccount: 'deleteAccount',
  ReceiptInformation : 'receiptInfromation',
  SeasonalPromotionDetail: 'seasonalPromotionDetail',
  NewsletterByDate: 'newsletterByDate',
  NewsletterDetail: 'newsletterDetail',
  MouPartners: 'mouPartners',
  InAppWebView: 'inAppWebView',
  MemberDirectory: 'memberDirectory',
  MemberDirectoryDetail: 'memberDirectoryDetail'
};

export default Screen;
